### ISSUE TITLE
签到运行报错

### ISSUE THREAD

**Issue by miaowmint** [jessfin/nssign#4]
今天签到运行报错如下，前几天也出现了这个问题，但是当时我把cookie.txt删除再运行就好了，今天发现并没有cookie.txt这个文件，也不是目录权限问题，我把权限改成777了也不行

```
Traceback (most recent call last):
  File "/data/nssign/main.py", line 62, in <module>
    data = json.loads(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.3/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.3/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.3/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by Agmes47** [comment]
Try to replace all `cookie.txt` in `main.go` with its corresponding absolute path, like `/home/user_name/nssgin/cookie.txt`.
